name: rabbit_mq
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.0
  mqtt_client: ^9.7.2
  jaguar: ^3.1.3
  sqlite3: ^1.9.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
